### ISSUE TITLE
Redirecting from this website

### ISSUE THREAD

**Issue by LandenSisk** [markoffline/markoffline.github.io#1]
# You can utilize this website as a redirect to the official website

Since you are already making a website for Krayon, you can use this website as a redirect using the ```<meta>```  tag

Here’s an example of how to use the meta tag:
```
<!DOCTYPE html>
   <head>
      <meta http-equiv="Refresh" content="0; url='http://www.krayonbox.com:3000'" />
   </head>
```

**Comment by sadiki0** [comment]
No. This is a personal site UwU. will add a link to krayon later tho.
